diff --git a/8.2/apache/Dockerfile b/8.2/apache/Dockerfile
index a5b0446..340899d 100644
--- a/8.2/apache/Dockerfile
+++ b/8.2/apache/Dockerfile
@@ -38,7 +38,8 @@ RUN set -ex \
 	&& pecl install redis-2.2.8 \
 	&& docker-php-ext-enable apcu memcached redis
 
-ENV OWNCLOUD_VERSION 8.2.7
+ARG OWNCLOUD_VERSION
+
 VOLUME /var/www/html
 
 RUN curl -fsSL -o owncloud.tar.bz2 \
